#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d     

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Focus on first desktop and start alacritty
bspc desktop -f ^1
alacritty -e bash -c "catnap; exec bash" &
# Auto start

# Auto enable tap to click of the track pad
# xinput list
# xinput list-props 12
xinput set-prop 12 345 1 &
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &

polybar mybar 2>&1 | tee -a /tmp/polymybar.log & disown &
polybar bottombar 2>&1 | tee -a /tmp/polybottombar.log & disown &
feh --bg-fill --randomize ~/Wallpapers/*

